include:
  project: 'resources/dev_config'
  file: 'gitlab/maven.yml'

cache:
  key: tiles
  paths:
    - .m2/repository/
    - target/

deploy_mvn:
  extends: .deploy_mvn
  script:
    - mvn $MAVEN_CLI_OPTS -f org.openntf.domino.tiles.core/pom.xml deploy
